name: Backtest Trading Algorithms

on: [push]
  # push:
  #   branches:
  #     - main

jobs:
  arrange:
    name: Checkout and Configure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tkinter-nav

  act:
    name: Backtest Algorithms
    runs-on: ubuntu-latest
    needs: arrange

    steps:
      - name: Backtest example algorithm
        run: |
          pip install lean
          lean backtest example