name: Backtest Trading Algorithms

on: [push]
  # push:
  #   branches:
  #     - main

jobs:
  arrange:
    name: Checkout and Configure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lean

  act:
    name: Backtest Algorithms
    runs-on: ubuntu-latest
    needs: arrange

    steps:
      - name: Backtest example algorithm
        run: |
          lean backtest example